public class HtmlTestHelper {

  public static String getHtml() {
    return "<!doctype html>\n" + "<html> \n" + " <head> \n"
        + "  <link rel=\"stylesheet\" href=\"./milk.css\" type=\"text/css\"> \n"
        + "  <link rel=\"shortcut icon\" href=\"/favicon.ico\"> \n"
        + "  <title>Welcome To MILK Kommunikations Ko-Op</title> \n" + " </head> \n" + " <body> \n"
        + "  <table class=\"milk-header\"> \n" + "   <tbody>\n" + "    <tr> \n"
        + "     <td><img src=\"./images/milk-icon.gif\" alt=\"milk.com icon\"></td> \n"
        + "     <td> <h1>Welcome To <span class=\"milk\">Milk</span> Kommunikations Ko-Op</h1> <h2>Your lactose pipeline.</h2> <h3>Established 1994.</h3> </td> \n"
        + "    </tr> \n" + "   </tbody>\n" + "  </table> \n" + "  <table class=\"ad\"> \n"
        + "   <tbody>\n" + "    <tr> \n"
        + "     <td> <!-- BEGIN CODE FROM TEH GOOGELS --> <script type=\"text/javascript\"><!--\n"
        + "google_ad_client = \"ca-pub-1482873655096887\";\n" + "/* Milk Home Page */\n"
        + "google_ad_slot = \"5490182709\";\n" + "google_ad_width = 468;\n"
        + "google_ad_height = 60;\n" + "//-->\n"
        + "</script> <script type=\"text/javascript\" src=\"https://pagead2.googlesyndication.com/pagead/show_ads.js\">\n"
        + "</script> <!-- END CODE FROM TEH GOOGELS --> </td> \n"
        + "     <td class=\"filler\"> <i>We love marmots.</i> <!--\n"
        + "  <p align=\"center\"><a href=\"http://milk.com/\"><img alt=\"Our sponsor!\"\n"
        + "  src=\"/images/c4.gif\"/></a></p>\n" + "  --> </td> \n" + "    </tr> \n"
        + "   </tbody>\n" + "  </table> \n" + "  <p class=\"Main\">Main Contents</p> \n"
        + "  <ul class=\"Main\"> \n"
        + "   <li><a href=\"home/danfuzz/\">Danfuzz's Home Page</a></li> \n" + "  </ul> \n"
        + "  <ul class=\"Main\"> \n"
        + "   <li><a href=\"mimu/\">Mimu: Music Demos and Library</a> \n" + "    <ul> \n"
        + "     <li><a href=\"mimu/awkward-js-music/\">AWKward JS Music</a></li><a href=\"mimu/awkward-js-music/\"> </a>\n"
        + "     <li><a href=\"mimu/awkward-js-music/\"></a><a href=\"mimu/filter-explorer/\">Filter Explorer</a></li><a href=\"mimu/filter-explorer/\"> </a>\n"
        + "     <li><a href=\"mimu/filter-explorer/\"></a><a href=\"mimu/pink-noise-explorer/\">Pink Noise Explorer</a></li><a href=\"mimu/pink-noise-explorer/\"> </a>\n"
        + "     <li><a href=\"mimu/pink-noise-explorer/\"></a><a href=\"mimu/triangle-wave-explorer/\">Triangle Wave Explorer</a></li><a href=\"mimu/triangle-wave-explorer/\"> </a>\n"
        + "    </ul><a href=\"mimu/triangle-wave-explorer/\"> </a></li><a href=\"mimu/triangle-wave-explorer/\"> </a>\n"
        + "   <li><a href=\"mimu/triangle-wave-explorer/\"></a><a href=\"barcode/\">Barcode Server</a></li> \n"
        + "   <li><a href=\"recipes/\">Dan's Favorite Recipes</a></li> \n"
        + "   <li><a href=\"fuzzboy/\">Fuzzboy</a> (Danfuzz produces music, a.k.a. Blatant Self-Promotion)</li> \n"
        + "   <li><a href=\"dj-danfuzz/\">DJ Danfuzz</a> (a.k.a. More Blatant Self-Promotion)</li> \n"
        + "   <li><a href=\"random-humor/\">The J. Random Humor Archive</a></li> \n"
        + "   <li><a href=\"true-stories/\">True Stories</a></li> \n"
        + "   <li><a href=\"wall-o-shame/\">Wall O' Shame</a></li> \n" + "  </ul> \n"
        + "  <p class=\"Main\">Metainformation</p> \n" + "  <ul class=\"Main\"> \n"
        + "   <li><a href=\"faq/\">The <span class=\"milk\">Milk</span> FAQ</a></li> \n"
        + "   <li><a href=\"whatsit/\">About the <span class=\"milk\">Milk</span> Logo</a></li> \n"
        + "   <li><a href=\"value/\">Not For Sale</a></li> \n"
        + "   <li><a href=\"feedback/\"><span class=\"milk\">Milk</span> Feedback</a></li> \n"
        + "  </ul> \n" + "  <p class=\"Main\">Milk.com Publication Network</p> \n"
        + "  <ul class=\"Main\"> \n"
        + "   <li><a href=\"http://doestheuniverseexist.com/\">Does the universe exist?</a></li> \n"
        + "   <li><a href=\"hourlykitten/\">Hourly Kitten</a></li> \n"
        + "   <li><a href=\"http://postham.org/\">Postham</a></li> \n" + "  </ul> \n" + "  <hr> \n"
        + "  <h2><span class=\"milk\">Milk</span> News</h2> \n"
        + "  <p><b>January 3, 2018</b></p> \n"
        + "  <p>I've now been working at <a href=\"https://slack.com\">Slack Technologies</a> for just over two years, mostly doing work on a new subsystem that has yet to go into production.</p> \n"
        + "  <p><b>Are you interested in buying my domain?</b></p>\n" + "  <p> </p>\n"
        + "  <p>Forget it. <a href=\"value/\"><strong>\"I got milk.com!\"</strong></a></p> \n"
        + "  <p align=\"center\"><img vspace=\"3\" hspace=\"5\" align=\"middle\" src=\"./images/bfz.gif\" alt=\"blink-free zone\"> milk.com is a blink-free zone.</p> \n"
        + "  <table class=\"footer\"> \n" + "   <tbody>\n" + "    <tr> \n"
        + "     <td>Site copyright © 1994&#x2013;2020 Dan Bornstein. All rights reserved.</td> \n"
        + "     <td><a href=\"/\">milk.com</a></td> \n" + "    </tr> \n" + "   </tbody>\n"
        + "  </table>  \n" + " </body>\n" + "</html>";
  }

}
